spring.application.name=z_one

# Servidor
server.port=8080

# Oracle Database
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=PRODUCTORA_BD
spring.datasource.password=productora123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Gemini API Key
gemini.api.key=TU_API_KEY_AQUI